function home(){nav('home');app.innerHTML=`
<section class="hero"><div><div class="eyebrow">Open · local-first · document/task/project-first</div><h1><span>The mobile OS beyond app silos.</span></h1><p class="lede">Agent OS treats people, projects, documents, tasks, events, places, messages, devices, and agents as first-class system entities rather than data trapped inside applications. Shared entity and action contracts, semantic history, malleable views, transclusion, and capability-secured agents make the whole system searchable, scriptable, inspectable, reversible, and portable across hardware.</p><div class="hero-actions"><a class="btn primary" href="#wiki/AOS-SRC-N001">Read the product vision</a><a class="btn" href="#compare">Compare architectures</a><a class="btn ghost" href="#tasks">Explore the work graph</a></div><p class="hero-note">The implementation is a native Rust-first stack with an owned microkernel. Android and Linux are limited to quarantined Pixel 9 evidence and temporary bring-up tools—not used as the product substrate.</p></div><div class="hero-visual"><div class="orbit a"></div><div class="orbit b"></div><span class="node n1">Person</span><span class="node n2">Project</span><span class="node n3">Agent plan</span><span class="node n4">History</span><div class="phone"><div class="screen"><div class="context">Project · Agent OS</div><div class="entity-title">Camera quality programme</div><div class="story"><div class="story-top"><h3>Today</h3><span class="chip">semantic history</span></div><p>RAW pipeline experiment updated the Pixel 9 feasibility claim.</p><span class="chip">EXP-021</span> <span class="chip">2 linked tasks</span></div><div class="story"><div class="story-top"><h3>Related document</h3><span class="chip">transclusion</span></div><p>Portable camera stack · sensor, ISP, 3A and computational stages.</p></div><div class="story"><div class="story-top"><h3>Agent proposal</h3><span class="chip">preview only</span></div><p>Compare the new tuning profile against the reference scene corpus.</p></div><div class="intent"><input value="What should I do next?" aria-label="IntentBox preview"><div class="suggestions"><span class="chip">Review plan</span><span class="chip">Open evidence</span><span class="chip">Run dry‑run</span></div></div></div></div></div></section>
<section class="section"><div class="section-head"><div class="eyebrow">The core shift</div><h2>First-class work, not first-class apps.</h2><p>Applications become replaceable providers and views. The durable things in a person’s life become system objects with identity, authority, history, actions, links, and multiple representations.</p></div><div class="feature-grid">
${feature('◫','Document / task / project first','Navigate by the thing you are doing, not by remembering which application owns it. Documents can contain views, tasks, discussions, data and transclusions.',['Document','Task','Project','Thread'])}
${feature('⌘','Actions are shared contracts','Every meaningful operation is typed, discoverable and available to UI, CLI, automation and agents under the same capability and confirmation rules.',['Action','Provider','Capability','Receipt'])}
${feature('◌','Semantic history and recovery','The system records meaningful state transitions, provenance and effects—supporting search, replay, undo or compensation instead of scattered app histories.',['Event','Snapshot','Undo','Provenance'])}
${feature('◇','Local and private by default','The user controls where data and logic live. Remote models and providers receive bounded, inspectable inputs instead of ambient access.',['Local-first','Policy','Encryption','Data class'])}
${feature('⌁','Malleable views and transclusion','The same entity can appear as a card, table, timeline, map, document block or agent context without copying opaque app state.',['View','Layout','Story','Transclusion'])}
${feature('◎','Agents with plans, not magic','Agents propose inspectable plans, request scoped capabilities, run in shadow or dry-run mode and leave execution receipts with costs and side effects.',['IntentBox','Plan','Dry-run','Receipt'])}
</div></section>
<section class="section"><div class="section-head"><div class="eyebrow">System-wide properties</div><h2>Everything important crosses app boundaries.</h2></div><div class="architecture"><div class="stack"><div class="layer product"><strong>Product surfaces</strong><span>Entities, live documents, IntentBox, FlexLight, stories, malleable views</span></div><div class="layer product"><strong>Portable system services</strong><span>Actions, history, identity, policy, storage, packages, sync, backup, agents</span></div><div class="layer native"><strong>Device-service contracts</strong><span>Camera, display, audio, network, modem, sensors, power, secure services</span></div><div class="layer native"><strong>Native Agent OS microkernel</strong><span>Capabilities, IPC, scheduling, address spaces, interrupts, time</span></div><div class="layer"><strong>Architecture ports and board packages</strong><span>QEMU, documented boards, open phone hardware, Pixel 9 research, future custom device</span></div></div><div class="rule-list"><div class="rule"><strong>One object, many surfaces</strong><p>A person is not one contact in five messenger databases. A project is not a folder plus a chat plus a board plus a calendar.</p></div><div class="rule"><strong>One action model, many callers</strong><p>The same typed action can be invoked from a button, command palette, script or agent—under different authority and confirmation policy.</p></div><div class="rule"><strong>Replaceable providers</strong><p>Transport, storage, rendering and hardware backends can change while entity and action semantics remain stable.</p></div><div class="rule"><strong>Evidence over promises</strong><p>Claims, experiments, risks and acceptance gates are part of the architecture and public engineering workflow.</p></div></div></div></section>
<section class="section"><div class="section-head"><div class="eyebrow">Explore the engineering system</div><h2>The portal is the executable map of the project.</h2><p>Every important object should lead somewhere useful: a specification, task, dependency, claim, experiment, source, decision, implementation artifact, or acceptance gate.</p></div><div class="feature-grid">
${feature('↗','Cross-linked Wiki','Read the complete Markdown corpus inside the portal, follow stable AOS links, render diagrams, and jump directly to editable GitHub sources.',['Specs','Research','Glossary','Prior art'])}
${feature('✓','Task and evidence graph','Inspect scope, acceptance criteria, dependencies, ownership, schedules, specifications, and live GitHub Issues for every planned work item.',['Task','Epic','Evidence','Dependency'])}
${feature('⌁','Interactive programme timeline','Filter the Gantt by phase, track, type, and status; click a bar to open its task; maintain local schedule drafts before publishing changes.',['Gantt','Milestone','Critical path','Draft'])}
</div><div class="hero-actions"><a class="btn primary" href="#wiki">Browse the Wiki</a><a class="btn" href="#tasks">Explore tasks</a><a class="btn" href="#gantt">Open the Gantt</a><a class="btn ghost" href="#api">Use the APIs</a></div></section>`}
function feature(icon,title,text,tags){return `<article class="feature"><div class="icon">${icon}</div><h3>${esc(title)}</h3><p>${esc(text)}</p><div class="first-class">${tags.map(x=>`<span>${esc(x)}</span>`).join('')}</div></article>`}
function compare(){nav('compare');app.innerHTML=`<div class="workspace-head"><div><div class="eyebrow">Architectural comparison</div><h1>iOS, Android, and Agent OS</h1><p class="muted">A paradigm comparison, not a claim that every planned Agent OS capability is already implemented.</p></div></div><div class="compare-wrap"><table class="compare"><thead><tr><th>Dimension</th><th>iOS</th><th>Android</th><th class="agent">Agent OS target</th></tr></thead><tbody>${comparisonRows().map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td class="agent">${r[3]}</td></tr>`).join('')}</tbody></table></div><section class="section"><div class="section-head"><div class="eyebrow">Not “more features”</div><h2>The differentiator is the system model.</h2><p>Agent OS is not trying to win by adding one more assistant, widget or sharing protocol. It changes what the operating system considers a durable object, an action, a view, a history event and an authority grant.</p></div></section>`}
function comparisonRows(){return [
['Primary unit','Application, document inside app','Application, activity/service and content provider','Person, project, task, document, event, place, message, device and agent are system entities'],
['Data authority','Mostly app and service silos','Mostly app/provider silos with vendor services','Local-first system authority with explicit providers, provenance and portable schemas'],
['Actions and automation','App Intents, Shortcuts and private frameworks','Intents, AppFunctions and heterogeneous automation APIs','One typed action/provider catalog shared by UI, CLI, scripts and agents'],
['History','Per-app state, backups and limited system recents','Per-app state, notifications, backups and activity history','Semantic system event log with source, authority, effect and reversible/compensating actions'],
['Agents','Assistant layered over selectively exposed app capabilities','Assistant layered over intents, screens and emerging app functions','Inspectable plans, capability grants, dry-run/shadow modes and execution receipts'],
['UI composition','Polished but mostly fixed first-party/app surfaces','Flexible ecosystem but still app-owned surfaces','Malleable views, transclusion, structured copy and reusable interaction contracts'],
['Settings and scripting','Partial Shortcuts/MDM/configuration coverage','Fragmented settings, intents, shell and vendor APIs','Config ↔ CLI/TUI ↔ API ↔ Settings ↔ GUI parity as a conformance goal'],
['Portability','Vertically integrated Apple hardware','Broad hardware with vendor fragmentation','Portable contracts above architecture ports, board packages and isolated user-space drivers'],
['Openness','Proprietary platform','Open base mixed with proprietary services and vendor layers','Open native stack, public contracts and evidence-driven hardware routes'],
['Business ecosystem','Hardware, services and App Store','OEM ecosystem, Play services and app stores','Open core plus certified devices, support, hosted services, integrations and provider marketplace']];}
