function workspaceHead(label,title,desc,actions=''){return `<div class="workspace-head"><div><div class="eyebrow">${esc(label)}</div><h1>${esc(title)}</h1>${desc?`<p class="muted">${desc}</p>`:''}</div><div class="hero-actions">${actions}</div></div>`}
function unique(field){return [...new Set(TASKS.map(t=>t[field]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}))}
function wiki(docId,anchor){nav('wiki');const cats=[...new Set(DOCS.map(d=>d.category))].sort();app.innerHTML=`${workspaceHead('Cross-linked knowledge base','Wiki','All canonical documents render inside the portal; GitHub remains the editable source.',`<a class="btn" href="${gh('/tree/main/engineering-bible/docs')}">Source ↗</a>`)}<div class="wiki-layout"><aside class="doc-sidebar"><div class="doc-filters"><input class="field search" id="doc-search" placeholder="Search ${DOCS.length||144} documents"><select class="field" id="doc-cat" style="width:100%;margin-top:7px"><option value="">All categories</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div class="doc-list" id="doc-list"></div></aside><section class="doc-view"><div class="doc-top"><span id="doc-status" class="muted">Select a document</span><div><button class="btn small" id="copy-doc">Copy link</button> <a class="btn small" id="edit-doc" href="#">Edit on GitHub ↗</a></div></div><article class="markdown" id="doc-content"><h1>Agent OS Wiki</h1><p>Select a document from the index. Internal links remain inside the portal.</p></article></section></div>`;let q='',cat='';const drawList=()=>{const xs=DOCS.filter(d=>(!q||[d.id,d.title,d.summary].join(' ').toLowerCase().includes(q.toLowerCase()))&&(!cat||d.category===cat));document.querySelector('#doc-list').innerHTML=xs.map(d=>`<a class="doc-item ${d.id===docId?'active':''}" href="#wiki/${encodeURIComponent(d.id)}"><span class="doc-id">${esc(d.id)}</span><strong>${esc(d.title)}</strong><small>${esc(d.category)} · ${esc(d.status)}</small></a>`).join('')||'<div class="status">No matching documents.</div>'};document.querySelector('#doc-search').oninput=e=>{q=e.target.value;drawList()};document.querySelector('#doc-cat').onchange=e=>{cat=e.target.value;drawList()};drawList();document.querySelector('#copy-doc').onclick=()=>navigator.clipboard.writeText(location.href);if(docId)openDoc(docId,anchor)}
function docSlug(s){return String(s||'').toLowerCase().trim().replace(/[^\w\s-]/g,'').replace(/[\s_]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')||'section'}
// Assign a stable id to every H2/H3 so the TOC, deep links and in-doc anchors resolve.
// Bible docs already ship explicit <a id> anchors; heading ids are added on top of them.
function tagHeadings(content){const used=new Set([...content.querySelectorAll('[id]')].map(el=>el.id));return [...content.querySelectorAll('h2,h3')].map(h=>{const level=h.tagName==='H3'?3:2,text=h.textContent.trim();if(h.id){used.add(h.id);return{id:h.id,text,level}}const base=docSlug(text);let cand=base,n=1;while(used.has(cand))cand=`${base}-${n++}`;used.add(cand);h.id=cand;return{id:cand,text,level}})}
function renderDocTOC(content,headings){if(headings.length<3)return;const nav=document.createElement('nav');nav.className='doc-toc';nav.setAttribute('aria-label','On this page');nav.innerHTML=`<strong>On this page</strong><ul>${headings.map(h=>`<li style="margin-left:${(h.level-2)*14}px"><a href="#${h.id}">${esc(h.text)}</a></li>`).join('')}</ul>`;const h1=content.querySelector('h1');if(h1&&h1.nextSibling)content.insertBefore(nav,h1.nextSibling);else content.insertBefore(nav,content.firstChild)}
function renderPrevNext(content,docId){const list=DOCS,i=list.findIndex(x=>x.id===docId);if(i<0)return;const prev=list[i-1],next=list[i+1],nav=document.createElement('nav');nav.className='doc-prevnext';nav.innerHTML=`${prev?`<a href="#wiki/${encodeURIComponent(prev.id)}">← ${esc(prev.id)} · ${esc(prev.title)}</a>`:'<span></span>'}${next?`<a href="#wiki/${encodeURIComponent(next.id)}">${esc(next.id)} · ${esc(next.title)} →</a>`:'<span></span>'}`;content.appendChild(nav)}
// Resolve a relative Markdown href (any filename, not only AOS-*) to a portal wiki
// route by matching against a loaded DOCS entry's path/basename. Returns null for
// external URLs or unknown files so those hrefs are left untouched.
function resolveDocLink(href){if(/^[a-z]+:/i.test(href)||href.startsWith('//'))return null;const m=href.match(/([^/#?]+)\.md(?:#(.+))?$/i);if(!m)return null;const stem=m[1],fname=stem+'.md',anchor=m[2]||'';const doc=DOCS.find(x=>x.file===fname||x.file.endsWith('/'+fname))||DOCS.find(x=>x.file.split('/').pop()===fname)||DOCS.find(x=>x.id===stem);return doc?{id:doc.id,anchor}:null}
// Cross-doc Markdown links become portal wiki routes; same-page #anchors scroll in
// place (a raw #hash would otherwise trigger the router and drop the reader out of the doc).
function wireDocLinks(content,docId){content.querySelectorAll('a[href]').forEach(a=>{const href=a.getAttribute('href')||'';const r=resolveDocLink(href);if(r){a.href=`#wiki/${encodeURIComponent(r.id)}${r.anchor?'/'+encodeURIComponent(r.anchor):''}`;return}if(href.startsWith('#')&&!href.startsWith('#wiki/')&&!href.startsWith('#/')){const id=decodeURIComponent(href.slice(1));if(!id)return;a.addEventListener('click',ev=>{const el=content.querySelector('#'+CSS.escape(id));if(el){ev.preventDefault();el.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'',`#wiki/${encodeURIComponent(docId)}/${encodeURIComponent(id)}`)}})}})}
async function renderMermaid(content){if(!window.mermaid)return;for(const n of [...content.querySelectorAll('code.language-mermaid')]){const box=document.createElement('div');box.className='mermaid';box.textContent=n.textContent;n.parentElement.replaceWith(box)}await mermaid.run({nodes:content.querySelectorAll('.mermaid')})}
let docRequestSeq=0;
async function openDoc(id,anchor=''){const d=DOCS.find(x=>x.id===id);if(!d)return;const seq=++docRequestSeq,content=document.querySelector('#doc-content'),status=document.querySelector('#doc-status'),edit=document.querySelector('#edit-doc');status.textContent=`${d.id} · ${d.status}`;edit.href=gh(`/edit/main/engineering-bible/docs/${d.file}`);content.innerHTML='<p class="muted">Loading document…</p>';try{const text=await fetch(raw('engineering-bible/docs/'+d.file),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.text()});if(seq!==docRequestSeq)return;content.innerHTML=window.marked?marked.parse(text.replace(/^---[\s\S]*?---\s*/,'')):`<pre>${esc(text)}</pre>`;const headings=tagHeadings(content);renderDocTOC(content,headings);renderPrevNext(content,d.id);wireDocLinks(content,d.id);await renderMermaid(content);if(seq!==docRequestSeq)return;if(anchor)setTimeout(()=>document.getElementById(anchor)?.scrollIntoView(),30)}catch(e){if(seq!==docRequestSeq)return;content.innerHTML=`<div class="status error">Could not load ${esc(d.file)}: ${esc(e.message)}</div>`}}
